pool/urls.py
from django.urls import path

from . import views

app_name = 'pool'
urlpatterns = [
    path('', views.GetTargetView.as_view(), name='index'),
    path('contribute/', views.UploadTargetView.as_view(), name='contribute'),
    path('thanks/', views.ThanksTemplateView.as_view(), name='thanks'),
    path('viewedTargets/', views.ViewedTargetsListView.as_view(), name='viewed_targets'),
    path('viewedTargets/reset/', views.ResetViewedTargets.as_view(), name='reset_viewed_targets'),
    path('target/<str:tid>/', views.target_detail, name='target_detail'),
    path('target/<str:tid>/reveal/', views.RevealTargetView.as_view(), name='reveal_target'),
    path('shared/target/<str:uuid>/', views.target_detail_public, name='shared_target_detail'),
    path('personalTargets/', views.PersonalTargetsView.as_view(), name="personal_targets"),
    path('personalTargets/new/', views.NewPersonalTargetView.as_view(), name="new_personal_target"),
    path('personalTarget/<str:tid>/', views.personal_target_detail, name='personal_target_detail'),
    path('personalTarget/<str:tid>/reveal/', views.RevealPersonalTargetView.as_view(), name='reveal_personal_target'),
    path('personalTarget/<str:tid>/conclude/', views.ConcludePersonalTargetView.as_view(), name='conclude_personal_target'),
    path('personalTarget/<str:tid>/return/', views.ReturnPersonalTargetView.as_view(), name='return_personal_target'),
    path('settings/', views.SettingsTemplateView.as_view(), name="user_settings"),
    path('settings/changePassword/', views.ChangePasswordView.as_view(), name="change_password")
]

pool/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import mark_safe

# Create your models here.
class Submission(models.Model):

    CATEGORIES = (
        ('PERSON', 'Person'),
        ('LIFEFORM', 'Lifeform'),
        ('OBJECT', 'Object'),
        ('LOCATION', 'Location'),
        ('EVENT', 'Event'),
        ('OTHER', 'Other')
    )

    LEVELS = (
        ('BEGINNER', 'Beginner'),
        ('INTERMEDIATE', ' Intermediate'),
        ('ADVANCED', 'Advanced')
    )

    submitted_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uploader')
    submission_date = models.DateTimeField(auto_now_add=True)
    moderated = models.BooleanField(default=False)
    moderated_date = models.DateTimeField(blank=True, null=True)
    moderated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='moderator')
    approved = models.BooleanField(default=False)
    rejection_reason = models.CharField(max_length=200, blank=True, null=True)
    category = models.CharField(max_length=12, choices=CATEGORIES, null=True, blank=True)
    level = models.CharField(max_length=12, choices=LEVELS, null=False, blank=False, default='ADVANCED')
    tasking = models.TextField(null=False, blank=False)
    target_description = models.CharField(max_length=255, null=False, blank=False)
    additional_feedback = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.target_description

    def save(self, *args, **kwargs):
        if self.id:
            self.pooltarget.category = self.category
            self.pooltarget.level = self.level
            self.pooltarget.save()
        super(Submission, self).save(*args, **kwargs)

    def image_tag(self):
        src = settings.MEDIA_URL + str(self.pooltarget.feedback_img)
        return mark_safe(f'<a href="{src}" target="blank"><img src="{src}" width="350" height="300" /></a>')

    def status(self):
        if self.moderated:
            if self.approved:
                return 'Approved'
            else:
                return 'Rejected'
        else:
            return '-'
    
    image_tag.short_description = 'Feedback Image'

    class Meta:
        ordering = ['-submission_date']

class PoolTarget(models.Model):

    category = models.CharField(max_length=12, null=True, blank=True)
    level = models.CharField(max_length=12, null=False, blank=False, default='ADVANCED')
    feedback_img = models.ImageField()
    feedback_img_phash = models.CharField(max_length=16, unique=True)
    tasking = models.TextField()
    target_description = models.CharField(max_length=255)
    additional_feedback = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=False)
    submission = models.OneToOneField(Submission, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.target_description


class Target(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    target_uid = models.CharField(max_length=22, unique=True)
    target_id = models.CharField(max_length=9)
    pool_target = models.ForeignKey(PoolTarget, on_delete=models.CASCADE, null=True)
    revealed = models.BooleanField(default=False)
    reveal_date = models.DateTimeField(blank=True, null=True)
    is_precog = models.BooleanField()
    inc_submitted = models.BooleanField(default=False)
    allowed_categories = models.CharField(max_length=64)
    level = models.CharField(max_length=12, default='ADVANCED')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.target_id

    class Meta:
        ordering = ['-created']

class PersonalTarget(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tasking = models.TextField()
    tid = models.CharField(max_length=9, null=True, blank=True)
    active = models.BooleanField(default=False)
    revealed = models.BooleanField(default=False)

pool/forms.py
from django import forms
from django.core.exceptions import ValidationError

from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox

class UploadTargetForm(forms.Form):
    LEVELS = (
        ('BEGINNER', 'Beginner'),
        ('INTERMEDIATE', ' Intermediate'),
        ('ADVANCED', 'Advanced')
    )
    level = forms.ChoiceField(choices=LEVELS, widget=forms.RadioSelect)
    additional_feedback = forms.CharField(widget=forms.Textarea(), required=False)
    tasking = forms.CharField(widget=forms.Textarea())
    target_description = forms.CharField(max_length=255)
    feedback_image = forms.ImageField()
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

class GetTargetForm(forms.Form):
    LEVELS = (
        ('BEGINNER', 'Beginner'),
        ('INTERMEDIATE', ' Intermediate'),
        ('ADVANCED', 'Advanced')
    )
    level = forms.ChoiceField(choices=LEVELS, widget=forms.RadioSelect)
    precognitive = forms.BooleanField(required=False)
    incsubmitted = forms.BooleanField(required=False)

    # def clean(self):
    #     cleaned_data = super().clean()

    #     categories = ['person', 'lifeform', 'object',
    #                   'location', 'event', 'other']
    #     selected_categories = list()
    #     for category in categories:
    #         if cleaned_data.get(category):
    #             selected_categories.append(category.upper())

    #     if not selected_categories:
    #         raise ValidationError('You need to select at least one category.')

    #     cleaned_data['selected_categories'] = selected_categories
    #     return cleaned_data

class NewPersonalTargetForm(forms.Form):
    tasking = forms.CharField(widget=forms.Textarea(), required=True)

pool/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.timezone import now
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.exceptions import ValidationError

from django.template.defaulttags import register

from pool.forms import UploadTargetForm, GetTargetForm, NewPersonalTargetForm
from pool.models import PoolTarget, Target, Submission, PersonalTarget
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View

from .utils import gen_tid, encrypt, decrypt

from random import randint
import imagehash
from PIL import Image
import io
import uuid, shortuuid
import markdown

# Create your views here.

'''
** Practice views
'''
class GetTargetView(LoginRequiredMixin, FormView):
    template_name = 'home.html'
    form_class = GetTargetForm
    success_url = '/pool/target/'

    def form_valid(self, form):
        if not form.cleaned_data['precognitive']:
            all_pooltargets = PoolTarget.objects.filter(level=form.cleaned_data['level'], active=True)
            done_targets = Target.objects.filter(pool_target__level=form.cleaned_data['level'],
                                                user=self.request.user).values_list('pool_target', flat=True)
            available_targets = all_pooltargets.exclude(pk__in=done_targets)
            if not form.cleaned_data['incsubmitted']:
                available_targets = available_targets.exclude(submission__submitted_by=self.request.user)
            count = available_targets.count()

            if count > 0:
                sel_target = available_targets[randint(0, count - 1)]
                
                tid = gen_tid()
                exists = Target.objects.filter(user=self.request.user, target_id=tid).exists()
                while exists:
                    tid = gen_tid()
                    exists = Target.objects.filter(user=self.request.user, target_id=tid).exists()

                target = Target()
                target.user = self.request.user
                target.target_id = tid
                target.target_uid = shortuuid.uuid()
                target.pool_target = sel_target
                target.is_precog = False
                target.level = form.cleaned_data['level']
                target.allowed_categories = ''
                target.save()

                self.success_url += tid
            else:
                form.add_error(None, ValidationError('There are no more available targets for you in the selected level.'))
                return self.form_invalid(form)
        else:
            tid = gen_tid()
            exists = Target.objects.filter(user=self.request.user, target_id=tid).exists()
            while exists:
                tid = gen_tid()
                exists = Target.objects.filter(user=self.request.user, target_id=tid).exists()

            target = Target()
            target.user = self.request.user
            target.target_id = tid
            target.target_uid = shortuuid.uuid()
            target.is_precog = True
            target.inc_submitted = form.cleaned_data['incsubmitted']
            target.allowed_categories = ''
            target.level = form.cleaned_data['level']  
            target.save()

            self.success_url += tid

        return super(GetTargetView, self).form_valid(form)

@login_required
def target_detail(request, tid):
    target = get_object_or_404(Target, target_id=tid, user=request.user)
    return render(request, 'target_detail.html', {'target':target})

def target_detail_public(request, uuid):
    target = get_object_or_404(Target, target_uid=uuid)
    return render(request, 'target_detail.html', {'target':target})

class RevealTargetView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        tid = kwargs['tid']
        target = get_object_or_404(Target, target_id=tid, user=request.user)

        if target.is_precog:
            available_targets_ = PoolTarget.objects.filter(level=target.level, active=True)
            if not target.inc_submitted:
                available_targets_ = available_targets_.exclude(submission__submitted_by=request.user)
            done_targets = Target.objects.filter(pool_target__level=target.level,
                                                user=self.request.user).values_list('pool_target', flat=True)
            available_targets = available_targets_.exclude(pk__in=done_targets)
            count = available_targets.count()
            if count == 0:
                available_targets = available_targets_
                count = available_targets.count()
            sel_target = available_targets[randint(0, count - 1)]
            target.pool_target = sel_target

        target.revealed = True
        target.reveal_date = now()
        target.save()

        return HttpResponseRedirect(reverse('pool:target_detail', kwargs={'tid': tid}))

'''
** Contribute views
'''
class UploadTargetView(LoginRequiredMixin, FormView):

    template_name = 'contribute.html'
    form_class = UploadTargetForm
    success_url = '/pool/thanks/'

    def form_valid(self, form):
        
        image = Image.open(form.cleaned_data['feedback_image'])
        # Downscale image
        image.thumbnail(settings.IMAGE_MAX_SIZE, Image.ANTIALIAS)
        phash = imagehash.phash(image)
        if not PoolTarget.objects.filter(feedback_img_phash=phash).exists():
            
            # Fix PNG
            if image.format == 'PNG':
                image = image.convert('RGB')

            image_io = io.BytesIO()
            image.save(image_io, format='JPEG')
            file = InMemoryUploadedFile(
                image_io, 'feedback_image',
                f'{uuid.uuid4().hex}.jpg',
                'image/jpeg',
                None, None
            )
            form.cleaned_data['feedback_image'] = file

            submission = Submission()
            submission.submitted_by = self.request.user
            submission.level = form.cleaned_data['level']
            submission.target_description = form.cleaned_data['target_description']
            submission.tasking = form.cleaned_data['tasking']
            if form.cleaned_data['additional_feedback']:
                submission.additional_feedback = form.cleaned_data['additional_feedback']
            submission.save()
            

            upload = PoolTarget()
            upload.level = form.cleaned_data['level']
            upload.target_description = form.cleaned_data['target_description']
            upload.tasking = form.cleaned_data['tasking']
            if form.cleaned_data['additional_feedback']:
                upload.additional_feedback = form.cleaned_data['additional_feedback']
            upload.feedback_img = form.cleaned_data['feedback_image']
            upload.feedback_img_phash = phash
            upload.submission = submission
            upload.save()
        '''
        else:
            form.add_error(None, ValidationError('Thank you, but this image appears to be already in our database.'))
            return self.form_invalid(form)
        '''

        return super(UploadTargetView, self).form_valid(form)

class ThanksTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'thanks.html'

'''
** Viewed targets views
'''
class ViewedTargetsListView(LoginRequiredMixin, ListView):

    model = Target
    context_object_name = 'targets'
    paginate_by = 10
    template_name = 'viewed_targets.html'

    def get_queryset(self):
        queryset = Target.objects.filter(user=self.request.user)
        return queryset

class ResetViewedTargets(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        Target.objects.filter(user=request.user).delete()
        return HttpResponseRedirect(reverse('pool:viewed_targets'))

'''
** Personal Targets
'''
class PersonalTargetsView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        target_count = PersonalTarget.objects.filter(user=request.user).count()
        try:
            current = PersonalTarget.objects.filter(user=request.user, active=True).get()
        except PersonalTarget.DoesNotExist:
            current = None
        return render(request, 'personal_targets.html', context={'target_count': target_count, 'current':current})

    def post(self, request, *args, **kwargs):
        target_count = PersonalTarget.objects.filter(user=request.user).count()
        if target_count:
            available = PersonalTarget.objects.filter(user=request.user).all()
            selected = available[randint(0, target_count - 1)]
            selected.active = True
            selected.tid = gen_tid()
            selected.save()
            return HttpResponseRedirect(reverse('pool:personal_target_detail', kwargs={'tid':selected.tid}))
        else:
            return HttpResponseRedirect(reverse('pool:personal_targets'))

class NewPersonalTargetView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        form = NewPersonalTargetForm(request.POST)
        if form.is_valid():
            personal_target = PersonalTarget()
            personal_target.user = request.user
            html = markdown.markdown(form.cleaned_data['tasking'], extensions=['sane_lists'])
            personal_target.tasking = encrypt(html)
            personal_target.save()
        return HttpResponseRedirect(reverse('pool:personal_targets'))

pool/templates/base_main.html
{% load static %}
{% load ganalytics_id %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta property="og:site_name" content="RV Me">
  {% block metatags %}{% endblock %}

  <title>RV Me - {% block title %}{% endblock %}</title>

  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <!-- Bootstrap and fontawesome core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/fontawesome/css/all.min.css' %}" rel="stylesheet">

  <link href="{% static 'css/styles_main.css' %}" rel="stylesheet">

  {% block custom_css %}{% endblock %}

  <script async src="https://www.googletagmanager.com/gtag/js?id={% ganalytics_id %}"></script>

</head>

<body>

  {% if not user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand text-dark" id="logo" href="{% url 'index' %}">RV Me <sup class="text-muted">BETA</sup></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-2 mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Community
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="https://reddit.com/r/remoteviewing">Reddit</a>
                <a class="dropdown-item" href="https://discord.gg/4sWvxzN">Discord</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/nykotar/rvme">GitHub</a>
            </li>
        </ul>
        <div class="ml-auto">
          <a href="{% url 'login' %}" class="btn btn-outline-dark" role="button">Log in</a>
          <a href="{% url 'signup' %}" class="btn btn-dark" role="button">Sign up</a>
        </div>
      </div>
    </nav>
  {% endif %}

  <div class="d-flex" id="wrapper">

    {% if user.is_authenticated %}
    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading"><a class="text-reset text-decoration-none" href="{% url 'pool:index' %}">RVMe <sup class="text-muted">BETA</sup></a></div>
      <div class="list-group list-group-flush">
        <a href="{% url 'pool:index' %}" class="list-group-item list-group-item-action bg-light {% if request.resolver_match.view_name == 'pool:index' %}active{% endif %}">
          <i class="fas fa-bullseye mr-2"></i> Practice
        </a>
        <a href="{% url 'pool:viewed_targets' %}" class="list-group-item list-group-item-action bg-light {% if request.resolver_match.view_name == 'pool:viewed_targets' %}active{% endif %}">
          <i class="fas fa-list-ul mr-2"></i> Viewed Targets
        </a>
        <a href="{% url 'pool:personal_targets' %}" class="list-group-item list-group-item-action bg-light {% if request.resolver_match.view_name == 'pool:personal_targets' %}active{% endif %}">
          <i class="fas fa-dot-circle mr-2"></i> Personal Targets
        </a>
        <a href="{% url 'pool:contribute' %}" class="list-group-item list-group-item-action bg-light {% if request.resolver_match.view_name == 'pool:contribute' %}active{% endif %}">
          <i class="fas fa-upload mr-2"></i> Contribute
        </a>
        <a href="{% url 'pool:user_settings' %}" class="list-group-item list-group-item-action bg-light {% if request.resolver_match.view_name == 'pool:user_settings' %}active{% endif %}">
          <i class="fas fa-cogs mr-2"></i> Settings
        </a>
        {% if perms.pool.change_submission %}
            <a href="/admin/pool/submission/?moderated__exact=0" class="list-group-item list-group-item-action bg-light">
              <i class="fas fa-list mr-2"></i> Approval Queue
            </a>
        {% endif %}
        <a href="/accounts/logout" class="list-group-item list-group-item-action bg-light">
          <i class="fas fa-sign-out-alt mr-2"></i> Log out
        </a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->
    {% endif %}

    <!-- Page Content -->
    <div id="page-content-wrapper">

      {% if user.is_authenticated %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <a class="btn btn-light" id="menu-toggle">
          <span class="navbar-toggler-icon"></span>
        </a>
      </nav>
      {% endif %}

      <div class="container-fluid">
        {% block content %}{% endblock %}
      </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });

    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })

    window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', '{% ganalytics_id %}', { 'anonymize_ip': true });
    
  </script>
  {% block custom_js %}{% endblock %}
</body>

</html>

pool/templates/personal_target_detail.html
{% extends "base_main.html" %}

{% block title %}{{ target.tid }}{% endblock %}
{% block content %}
  {% if not target.revealed %}
    <div class="container-fluid">
      <div class="d-flex justify-content-center align-items-center" style="margin-top: 15%">
        <form action="{% url 'pool:reveal_personal_target' target.tid %}" method="POST">
          {% csrf_token %}
          <button type="submit" id="tid" class="btn btn-outline-dark btn-xlg">{{ target.tid }}</button>
        </form>
      </div>
    </div>
  {% else %}
    <div class="container mt-4">
      <div class="mb-3">
          <h1 style="display: inline-block">{{ target.tid }}</h1>
      </div>
      {{ target.tasking|decryptTxt|safe }}
    </div>
    <div class="container mt-5">
      <div class="form-group">
        <form action="{% url 'pool:conclude_personal_target' target.tid %}" method="POST" class="d-inline-block">
          {% csrf_token %}
          <button type="submit" id="tid" class="btn btn-sm btn-dark">Conclude target</button>
        </form>
        <form action="{% url 'pool:return_personal_target' target.tid %}" method="POST" class="d-inline-block">
          {% csrf_token %}
          <button type="submit" id="tid" class="btn btn-sm btn-link">Return target to the pool</button>
        </form>
      </div>
    </div>
  {% endif %}
{% endblock %}

pool/templates/personal_targets.html
{% extends "base_main.html" %}
{% load static %}

{% block title %}Personal Targets{% endblock %}
{% block custom_css %}<link rel="stylesheet" href="{% static 'css/easymde.min.css' %}">{% endblock %}
{% block content %}

  {% if current %}
    <div class="alert alert-warning" role="alert">
      You have a personal target pending - <b>{{ current.tid }}</b>. Click <a href="{% url 'pool:personal_target_detail' current.tid %}" class="alert-link">here</a> to resume or <form action="{% url 'pool:return_personal_target' current.tid %}" style="display:inline" method="POST">{% csrf_token %}<button style="padding:0;background: none;border: none;text-decoration: underline;" class="alert-link" type="submit">here</button></form> to send the target back to the pool.
    </div>
  {% endif %}

  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success" role="alert">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}

  <div class="container mt-4">
    <h1 class="mt-4 mb-4">Personal Targets</h1>
    <div class="form-group">
      <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#newPersonalTargetModal">
        New Target
      </button>
    </div>
    <br/>
    <div class="card text-center" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Targets</h5>
        <p class="card-text target-count">{{ target_count }}</p>
        {% if target_count > 0 and not current %}
          <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-dark" name="tasking">Get target</button>
          </form>
        {% endif %}
      </div>
    </div>
  </div>


  <!-- Modal -->
  <div class="modal fade" id="newPersonalTargetModal" tabindex="-1" role="dialog" aria-labelledby="newPersonalTargetModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="newPersonalTargetModalTitle">New Personal Target</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-bs-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{% url 'pool:new_personal_target' %}" method="POST">
          {% csrf_token %}
          <div class="modal-body">
            <p>Write the tasking for your target:</p>
            <textarea id="tasking" name="tasking"></textarea>
            <small class="text-muted">Personal targets cannot be edited after added to the pool. The tasking is encrypted in the database.</small>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-dark">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

{% block custom_js %}
<script src="{% static 'js/easymde.min.js' %}"></script>
<script>
  var easyMDE = new EasyMDE({element: $('#tasking')[0], 
  toolbar: ["bold", "italic", "heading", "|", "unordered-list", "ordered-list", "|", "link", "image", "|", "preview", "side-by-side", "fullscreen", "|", "guide"]});
</script>
{% endblock %}

pool/templates/settings.html
{% extends "base_main.html" %}

{% block title %}Submit target{% endblock %}
{% block content %}

  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning" role="alert">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}

  <div class="container">
    <h1 class="mt-4 mb-4">Settings</h1>
    <div class="row">
      <div class="col col-xl-6 col-lg-7 col-md-8">
        <h3 class="mt-4 mb-4">Old password</h3>
        <form method="POST" action="{% url 'pool:change_password' %}">
          {% csrf_token %}
          <div class="mb-3">
            <label for="old_password" class="form-label">Current password</label>
            {{ form.old_password.errors }}
            <input type="password" class="form-control" id="old_password" name="old_password">
          </div>
          <div class="mb-3">
            <label for="new_password1" class="form-label">New password</label>
            {{ form.new_password1.errors }}
            <input type="password" class="form-control" id="new_password1" name="new_password1">
          </div>
          <div class="mb-3">
            <label for="new_password2" class="form-label">Confirm new password</label>
            <input type="password" class="form-control" id="new_password2" name="new_password2">
          </div>
          {{ form.new_password2.errors }}
          {{ form.non_field_errors }}
          <button type="submit" class="btn btn-secondary">Submit</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

pool/templates/thanks.html
{% extends "base_main.html" %}

{% block title %}Thank you{% endblock %}
{% block content %}
<div class="container mt-4">
    <h1>Thank you for your contribution!</h1>
    <h3 class="font-weight-light">Your target will be available to view once approved by a moderator.</h3>
    <br/>
    <a class="text-dark" href="{% url 'pool:index' %}">Back</a> | <a class="text-dark" href="{% url 'pool:contribute' %}">Submit another</a>
</div>
{% endblock %}